[match]
foreground = "white"
background = "blue"
underline = 1

["(?<=# )(.*)(?=$)"]
font=["Helvetica", 18, "bold"]

["\\*(.*?)\\*"]
font=["Helvetica", 12, "italic"]

["(?<=## )(.*)(?=$)"]
font=["Helvetica", 14, "bold"]

["(?<=### )(.*)(?=$)"]
font=["Helvetica", 12, "bold"]

["(?i)\\b((?:https?://|www\\d{0,3}[.]|[a-z0-9.\\-]+[.][a-z]{2,4}/)(?:[^\\s()<>]+|\\(([^\\s()<>]+|(\\([^\\s()<>]+\\)))*\\))+(?:\\(([^\\s()<>]+|(\\([^\\s()<>]+\\)))*\\)|[^\\s`!()[\\]{};:'\".,<>?«»“”‘’]))"]
foreground = "lightblue"
underline = 1
clickable = 1

# commented out for now
["<img>(.*?)</img>"]
underline = 1
foreground = "lightgreen"
image_file = 1

["(?<=\\$)(.*)(?=\\$)"]
foreground = "yellow"
background = "black"
render_latex = 1

["```([\\s\\S]*?)```"]
foreground = 'black'
background = "gray"
multiline = 1